[project]
name = "file-renamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2txt>=0.9",
    "huggingface-hub>=1.30.0",
    "llama-cpp-python==0.1.9",
    "ollama>=0.6.2",
    "openpyxl>=3.1.5",
    "pathlib>=1.0.1",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "sentence-transformers>=6.0.1",
]
